---
# File: playbooks/report_connectivity.yml
# Created by: Anthony Pagan
# Date: 2023-07-27
# License: MIT
# Description: This playbook tests if Ansible can connect to all hosts
#     and saves a report of any hosts that cannot be connected to.
#

- name: "Report: Connectivity"
  hosts: all:!Out_of_service
  gather_facts: false
  strategy: linear

  vars:
    # Connectivity report file
    report_file: "./connectivity_report.csv"

  tasks:
    - name: Test connectivity to host
      ansible.builtin.ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true
      tags:
        - connectivity

    - name: Save connectivity report to file
      ansible.builtin.lineinfile:
        path: "{{ report_file }}"
        line: "{{ inventory_hostname }},{{ ping_result.msg }}"
        create: true
        mode: '0644' # -rw-r--r--
        insertafter: EOF
      when: ping_result.msg is defined and ping_result.msg != "pong"
      delegate_to: localhost
      tags:
        - connectivity
